# Generated by Django 5.1.6 on 2025-03-02 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Bed Sitter', 'Bed Sitter'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom'), ('Three Bedroom', 'Three Bedroom'), ('Apartment', 'Apartment')], max_length=50),
        ),
    ]
