# Generated by Django 5.1.6 on 2025-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_location_property_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
