# Generated by Django 5.1.6 on 2025-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_property_county_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='vacancy',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], max_length=20, null=True),
        ),
    ]
