# Generated by Django 5.1.6 on 2025-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_property_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(null=True, upload_to='property_videos/'),
        ),
    ]
