# Generated by Django 5.1.6 on 2025-03-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_property_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='video',
        ),
    ]
