# Generated by Django 5.1.6 on 2025-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_property_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
    ]
